# Generated by Django 3.2.25 on 2025-06-24 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HotelApp', '0004_auto_20250624_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='price',
            new_name='hotel_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='Hotel_Name',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(to='HotelApp.Amenities'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(default='no data', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='no details'),
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_type', models.CharField(choices=[('Pre Paid', 'Pre Paid'), ('Post Paid', 'Post Paid')], max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='HotelApp.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
