# Generated by Django 3.2.25 on 2025-06-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0005_auto_20250624_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
